services:
  db:
    image: postgres:latest
    container_name: slither_db
    environment:
      POSTGRES_USER: slither
      POSTGRES_PASSWORD: slither
      POSTGRES_DB: slither
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
